appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: NJkyxXSyPoqIdYxnSf8BZ2gIWX0Isx7Uv8eJK2IjfuIH1aDoAmh+M8YVQAi/1Wl9wcNRHDb/rKTNWgg8pc2YK9IgDje+LqTOeEEt0zk1YCSV0+AEJemwaIIi+6pc+5VNCS2U0yfXrvN4QcBp/BwvehnovZuBw8nTR/LS0ShFRG7NArMUqhM8URsLsUXKZ2zxpg84d00+b9C4kDOsJJxrLf0sQy9MK/EnaSFB9u5nS1lWEVzZ2zkpPP7g2pWKeSLXchlWkyYGPR/uh05GvuzvdLjys7RK48L7TJA3uoL1GI7eMuMjv4mNMHyUuDMrotlcujLOWj0p1EW2k/gCJryrcaHUSYj8dvdqHMbU96oO95x6jD4BUjTio7TCGLLZg+hrCTHxRvWsn+6I+QXH79yRbu4oXhPdCf7YuJ5QNhHvkuXGoNXlPvimNwLAaSS+uQnTpDq7kDee6Gh5ikmL7JIMEcyWhvBmxxqBS4i4vKJuY/JJAIWZLW7+QCWOT6rw1zYoJlJ+nUm5MehkmOajrEeI80NbmEtM5hUL2EQKeuobXW4M5p1wqV02igk0WIQmJuRNtjw8JlzFMB76/BDsMbzoklUM/g2CcREsH/L6K/jJNlD6f+Vp72Uy8sMUGDmGovo1Rbcc3dKi+bOomTrdlyQ0IicUUU91g5LLiyFgd8Uzxf8=
conda_forge_output_validation: true
